version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
  
  api:
    image: fortapi
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - 5000:5000
    environment:
        - APP_SETTINGS=ProductionConfig
        - DATABASE_URL=postgres://postgres:example@db:5432/postgres
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080