"""empty message

Revision ID: 0ffe25401289
Revises: 
Create Date: 2018-11-11 19:05:26.668905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffe25401289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('eliminations', sa.Integer(), nullable=False),
    sa.Column('weapon_damage', sa.Integer(), nullable=False),
    sa.Column('other_damage', sa.Integer(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('damage_structures', sa.Integer(), nullable=False),
    sa.Column('materials_gathered', sa.Integer(), nullable=False),
    sa.Column('materials_used', sa.Integer(), nullable=False),
    sa.Column('total_traveled', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('total_players', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replays')
    # ### end Alembic commands ###
