"""empty message

Revision ID: 94687b9b964a
Revises: 0ffe25401289
Create Date: 2019-01-05 19:34:34.720043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94687b9b964a'
down_revision = '0ffe25401289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminations', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('weapon_damage', sa.Integer(), nullable=False),
    sa.Column('other_damage', sa.Integer(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('damage_structures', sa.Integer(), nullable=False),
    sa.Column('materials_gathered', sa.Integer(), nullable=False),
    sa.Column('materials_used', sa.Integer(), nullable=False),
    sa.Column('total_traveled', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('total_players', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elimination',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('replay', sa.Integer(), nullable=True),
    sa.Column('eliminator', sa.String(length=255), nullable=False),
    sa.Column('eliminated', sa.String(length=255), nullable=False),
    sa.Column('knocked', sa.Boolean(), nullable=True),
    sa.Column('weapon_type', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['replay'], ['replay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('replays')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replays',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eliminations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weapon_damage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('other_damage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revives', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('damage_taken', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('damage_structures', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('materials_gathered', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('materials_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_traveled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_players', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='replays_pkey')
    )
    op.drop_table('elimination')
    op.drop_table('replay')
    # ### end Alembic commands ###
