"""empty message

Revision ID: dadfea8a2a73
Revises: 7e4f18ddc578
Create Date: 2019-01-15 21:46:27.145543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dadfea8a2a73'
down_revision = '7e4f18ddc578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('replay_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('eliminations', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('weapon_damage', sa.Integer(), nullable=False),
    sa.Column('other_damage', sa.Integer(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('damage_structures', sa.Integer(), nullable=False),
    sa.Column('materials_gathered', sa.Integer(), nullable=False),
    sa.Column('materials_used', sa.Integer(), nullable=False),
    sa.Column('total_traveled', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['replay_id'], ['replay.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('replay', sa.Column('guid', sa.String(length=128), nullable=False))
    op.add_column('replay', sa.Column('release', sa.String(length=128), nullable=False))
    op.add_column('replay', sa.Column('version', sa.Integer(), nullable=False))
    op.drop_column('replay', 'title')
    op.drop_column('replay', 'damage_taken')
    op.drop_column('replay', 'other_damage')
    op.drop_column('replay', 'total_traveled')
    op.drop_column('replay', 'damage_structures')
    op.drop_column('replay', 'materials_used')
    op.drop_column('replay', 'revives')
    op.drop_column('replay', 'assists')
    op.drop_column('replay', 'eliminations')
    op.drop_column('replay', 'username')
    op.drop_column('replay', 'position')
    op.drop_column('replay', 'weapon_damage')
    op.drop_column('replay', 'accuracy')
    op.drop_column('replay', 'materials_gathered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replay', sa.Column('materials_gathered', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('accuracy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('weapon_damage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('eliminations', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('revives', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('materials_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('damage_structures', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('total_traveled', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('other_damage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('damage_taken', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('replay', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('replay', 'version')
    op.drop_column('replay', 'release')
    op.drop_column('replay', 'guid')
    op.drop_table('stats')
    # ### end Alembic commands ###
